export const quizData = [
  {
    id: 1,
    topic: "Weekend activities",
    correct_order: ["s4", "s2", "s1", "s3", "s5"], // Thứ tự logic theo ảnh
    sentences: [
      {
        id: "s1",
        text: "After receiving the prize, the children's activities and competitions began.",
        words: [
          { w: "After", m: "Sau khi" },
          { w: "receiving", m: "nhận" },
          { w: "the", m: "mạo từ" },
          { w: "prize", m: "giải thưởng" },
          { w: "the", m: "mạo từ" },
          { w: "children's", m: "của trẻ em" },
          { w: "activities", m: "hoạt động" },
          { w: "and", m: "và" },
          { w: "competitions", m: "cuộc thi" },
          { w: "began", m: "bắt đầu" },
        ],
      },
      {
        id: "s2",
        text: "Sixty men and women ran in this, and Ms Kamur won with a very fast time",
        words: [
          { w: "Sixty", m: "Sáu mươi" },
          { w: "men", m: "đàn ông" },
          { w: "and", m: "và" },
          { w: "women", m: "phụ nữ" },
          { w: "ran", m: "đã chạy" },
          { w: "in this", m: "trong cuộc đua này" },
          { w: "and", m: "và" },
          { w: "Ms Kamur", m: "Cô Kamur" },
          { w: "won", m: "đã thắng" },
          { w: "with", m: "với" },
          { w: "a", m: "một" },
          { w: "very", m: "rất" },
          { w: "fast", m: "nhanh" },
          { w: "time", m: "thời gian" },
        ],
      },
      {
        id: "s3",
        text: "These activities included football, jumping, and swimming, and they had lots of fun.",
        words: [
          { w: "These", m: "Những... này" },
          { w: "activities", m: "hoạt động" },
          { w: "included", m: "bao gồm" },
          { w: "football", m: "bóng đá" },
          { w: "jumping", m: "nhảy" },
          { w: "and", m: "và" },
          { w: "swimming", m: "bơi lội" },
          { w: "and", m: "và" },
          { w: "they", m: "họ" },
          { w: "had", m: "đã có" },
          { w: "lots of", m: "nhiều" },
          { w: "fun", m: "niềm vui" },
        ],
      },
      {
        id: "s4",
        text: "It started early on Saturday morning with a ten-mile race for adults.",
        words: [
          { w: "It", m: "Nó (lễ hội)" },
          { w: "started", m: "bắt đầu" },
          { w: "early", m: "sớm" },
          { w: "on", m: "vào" },
          { w: "Saturday", m: "Thứ 7" },
          { w: "morning", m: "buổi sáng" },
          { w: "with", m: "với" },
          { w: "a", m: "một" },
          { w: "ten-mile", m: "mười dặm" },
          { w: "race", m: "cuộc đua" },
          { w: "for", m: "cho" },
          { w: "adults", m: "người lớn" },
        ],
      },
      {
        id: "s5",
        text: "They were all very hungry after all these, so they enjoyed tasty food and drinks with their parents",
        words: [
          { w: "They", m: "Họ" },
          { w: "were", m: "đã" },
          { w: "all", m: "tất cả" },
          { w: "very", m: "rất" },
          { w: "hungry", m: "đói" },
          { w: "after", m: "sau" },
          { w: "all these", m: "tất cả những việc này" },
          { w: "so", m: "vì vậy" },
          { w: "they", m: "họ" },
          { w: "enjoyed", m: "thưởng thức" },
          { w: "tasty", m: "ngon" },
          { w: "food", m: "thức ăn" },
          { w: "and", m: "và" },
          { w: "drinks", m: "đồ uống" },
          { w: "with", m: "cùng với" },
          { w: "their", m: "của họ" },
          { w: "parents", m: "bố mẹ" },
        ],
      },
    ],
  },

  {
    id: 2,
    topic: "Film",
    correct_order: ["s3", "s2", "s5", "s4", "s1"],
    sentences: [
      {
        id: "s1",
        text: "Things have changed over time, and some of them have earned millions of dollars after appearing in films",
        words: [
          { w: "Things", m: "Mọi thứ" },
          { w: "have changed", m: "đã thay đổi" },
          { w: "over time", m: "theo thời gian" },
          { w: "and", m: "và" },
          { w: "some", m: "một số" },
          { w: "of them", m: "trong số họ" },
          { w: "have earned", m: "đã kiếm được" },
          { w: "millions", m: "hàng triệu" },
          { w: "dollars", m: "đô la" },
          { w: "after", m: "sau khi" },
          { w: "appearing", m: "xuất hiện" },
          { w: "in films", m: "trong phim" },
        ],
      },
      {
        id: "s2",
        text: "This is because they were black and white, and there was no sound.",
        words: [
          { w: "This", m: "Điều này" },
          { w: "is because", m: "là vì" },
          { w: "they", m: "chúng (phim)" },
          { w: "were", m: "đã là" },
          { w: "black and white", m: "đen trắng" },
          { w: "and", m: "và" },
          { w: "there was", m: "đã không có" },
          { w: "no sound", m: "âm thanh" },
        ],
      },
      {
        id: "s3",
        text: "The films in that period were different from the films of today.",
        words: [
          { w: "The films", m: "Những bộ phim" },
          { w: "in", m: "trong" },
          { w: "that period", m: "thời kỳ đó" },
          { w: "were", m: "đã" },
          { w: "different from", m: "khác với" },
          { w: "the films", m: "những bộ phim" },
          { w: "of today", m: "ngày nay" },
        ],
      },
      {
        id: "s4",
        text: "This lack of money mostly affected actors, and they didn't earn much",
        words: [
          { w: "This lack", m: "Sự thiếu hụt này" },
          { w: "of money", m: "về tiền bạc" },
          { w: "mostly", m: "chủ yếu" },
          { w: "affected", m: "ảnh hưởng đến" },
          { w: "actors", m: "diễn viên" },
          { w: "and", m: "và" },
          { w: "they", m: "họ" },
          { w: "didn't earn", m: "đã không kiếm được" },
          { w: "much", m: "nhiều" },
        ],
      },
      {
        id: "s5",
        text: "In addition to these technical limitations, film producers also had a very low budget",
        words: [
          { w: "In addition to", m: "Ngoài" },
          { w: "these", m: "những... này" },
          { w: "technical", m: "kỹ thuật" },
          { w: "limitations", m: "hạn chế" },
          { w: "film producers", m: "các nhà sản xuất phim" },
          { w: "also", m: "cũng" },
          { w: "had", m: "đã có" },
          { w: "a very low", m: "một... rất thấp" },
          { w: "budget", m: "ngân sách" },
        ],
      },
    ],
  },
  
  {
    id: 3,
    topic: "Transportation",
    correct_order: ["s5", "s1", "s4", "s2", "s3"],
    sentences: [
      {
        id: "s1",
        text: "The invention of cars and trains had changed everything and made travelling cheaper.",
        words: [
          { w: "The", m: "mạo từ" },
          { w: "invention", m: "sự phát minh" },
          { w: "of", m: "của" },
          { w: "cars", m: "xe hơi" },
          { w: "and", m: "và" },
          { w: "trains", m: "tàu hỏa" },
          { w: "had changed", m: "đã thay đổi" },
          { w: "everything", m: "mọi thứ" },
          { w: "and", m: "và" },
          { w: "made", m: "làm cho" },
          { w: "travelling", m: "việc đi lại" },
          { w: "cheaper", m: "rẻ hơn" },
        ],
      },
      {
        id: "s2",
        text: "Because flying with them is so fast, more people now go abroad for holiday and business.",
        words: [
          { w: "Because", m: "Bởi vì" },
          { w: "flying", m: "việc bay" },
          { w: "with", m: "với" },
          { w: "them", m: "chúng (máy bay)" },
          { w: "is", m: "thì" },
          { w: "so", m: "rất" },
          { w: "fast", m: "nhanh" },
          { w: "more", m: "nhiều... hơn" },
          { w: "people", m: "người" },
          { w: "now", m: "giờ đây" },
          { w: "go", m: "đi" },
          { w: "abroad", m: "ra nước ngoài" },
          { w: "for", m: "cho" },
          { w: "holiday", m: "kỳ nghỉ" },
          { w: "and", m: "và" },
          { w: "business", m: "công tác/kinh doanh" },
        ],
      },
      {
        id: "s3",
        text: "It is more convenient to travel to other part of the world due to the improvement in transports",
        words: [
          { w: "It", m: "Nó" },
          { w: "is", m: "thì" },
          { w: "more", m: "hơn" },
          { w: "convenient", m: "tiện lợi" },
          { w: "to travel", m: "để đi lại" },
          { w: "to", m: "đến" },
          { w: "other", m: "khác" },
          { w: "part", m: "phần/nơi" },
          { w: "of", m: "của" },
          { w: "the", m: "mạo từ" },
          { w: "world", m: "thế giới" },
          { w: "due to", m: "nhờ vào/do" },
          { w: "the", m: "mạo từ" },
          { w: "improvement", m: "sự cải thiện" },
          { w: "in", m: "trong" },
          { w: "transports", m: "giao thông vận tải" },
        ],
      },
      {
        id: "s4",
        text: "After these two means of transport, travelling becomes even easier with airplanes",
        words: [
          { w: "After", m: "Sau" },
          { w: "these", m: "những... này" },
          { w: "two", m: "hai" },
          { w: "means", m: "phương tiện" },
          { w: "of", m: "về" },
          { w: "transport", m: "vận tải" },
          { w: "travelling", m: "việc đi lại" },
          { w: "becomes", m: "trở nên" },
          { w: "even", m: "thậm chí" },
          { w: "easier", m: "dễ dàng hơn" },
          { w: "with", m: "với" },
          { w: "airplanes", m: "máy bay" },
        ],
      },
      {
        id: "s5",
        text: "In the past, transportation was only available to the rich.",
        words: [
          { w: "In", m: "Trong" },
          { w: "the", m: "mạo từ" },
          { w: "past", m: "quá khứ" },
          { w: "transportation", m: "giao thông" },
          { w: "was", m: "đã là" },
          { w: "only", m: "chỉ" },
          { w: "available", m: "có sẵn/dành cho" },
          { w: "to", m: "cho" },
          { w: "the", m: "mạo từ" },
          { w: "rich", m: "người giàu" },
        ],
      },
    ],
  },
  {
    id: 4,
    topic: "New Café in Town",
    correct_order: ["s3", "s1", "s5", "s2", "s4"],
    sentences: [
      {
        id: "s1",
        text: "Despite the crowd, they found me a nice table and brought me a menu.",
        words: [
          { w: "Despite", m: "Mặc dù" },
          { w: "the", m: "mạo từ" },
          { w: "crowd", m: "đám đông" },
          { w: "they", m: "họ (nhân viên)" },
          { w: "found", m: "đã tìm cho" },
          { w: "me", m: "tôi" },
          { w: "a", m: "một" },
          { w: "nice", m: "đẹp/tốt" },
          { w: "table", m: "cái bàn" },
          { w: "and", m: "và" },
          { w: "brought", m: "đã mang đến" },
          { w: "me", m: "cho tôi" },
          { w: "a", m: "một" },
          { w: "menu", m: "thực đơn" },
        ],
      },
      {
        id: "s2",
        text: "I had to choose one of those, so I decided to choose the most expensive sandwich.",
        words: [
          { w: "I", m: "Tôi" },
          { w: "had to", m: "đã phải" },
          { w: "choose", m: "chọn" },
          { w: "one", m: "một" },
          { w: "of", m: "trong số" },
          { w: "those", m: "những thứ đó" },
          { w: "so", m: "vì vậy" },
          { w: "I", m: "tôi" },
          { w: "decided", m: "đã quyết định" },
          { w: "to choose", m: "chọn" },
          { w: "the", m: "mạo từ" },
          { w: "most", m: "nhất" },
          { w: "expensive", m: "đắt tiền" },
          { w: "sandwich", m: "bánh mì kẹp" },
        ],
      },
      {
        id: "s3",
        text: "It was full of people, and the staff were working hard on their first day.",
        words: [
          { w: "It", m: "Nó (quán cà phê)" },
          { w: "was", m: "đã" },
          { w: "full of", m: "đầy/đông nghẹt" },
          { w: "people", m: "người" },
          { w: "and", m: "và" },
          { w: "the", m: "mạo từ" },
          { w: "staff", m: "nhân viên" },
          { w: "were working", m: "đang làm việc" },
          { w: "hard", m: "chăm chỉ" },
          { w: "on", m: "vào" },
          { w: "their", m: "của họ" },
          { w: "first", m: "đầu tiên" },
          { w: "day", m: "ngày" },
        ],
      },
      {
        id: "s4",
        text: "It was really good with cheese topping, and I would definitely go back to this place.",
        words: [
          { w: "It", m: "Nó (món ăn)" },
          { w: "was", m: "đã" },
          { w: "really", m: "thực sự" },
          { w: "good", m: "ngon/tốt" },
          { w: "with", m: "với" },
          { w: "cheese", m: "phô mai" },
          { w: "topping", m: "lớp phủ bên trên" },
          { w: "and", m: "và" },
          { w: "I", m: "tôi" },
          { w: "would", m: "sẽ" },
          { w: "definitely", m: "chắc chắn" },
          { w: "go back", m: "quay lại" },
          { w: "to", m: "đến" },
          { w: "this", m: "này" },
          { w: "place", m: "địa điểm/nơi" },
        ],
      },
      {
        id: "s5",
        text: "When I first looked at the menu, I was disappointed since I hoped to see a variety of dishes.",
        words: [
          { w: "When", m: "Khi" },
          { w: "I", m: "tôi" },
          { w: "first", m: "lần đầu" },
          { w: "looked at", m: "nhìn vào" },
          { w: "the", m: "mạo từ" },
          { w: "menu", m: "thực đơn" },
          { w: "I", m: "tôi" },
          { w: "was", m: "đã" },
          { w: "disappointed", m: "thất vọng" },
          { w: "since", m: "vì" },
          { w: "I", m: "tôi" },
          { w: "hoped", m: "đã hy vọng" },
          { w: "to see", m: "thấy" },
          { w: "a", m: "một" },
          { w: "variety", m: "sự đa dạng" },
          { w: "of", m: "của/các loại" },
          { w: "dishes", m: "món ăn" },
        ],
      },
    ],
  },
  {
    id: 5,
    topic: "Writing about a place",
    correct_order: ["s4", "s1", "s2", "s3", "s5"],
    sentences: [
      {
        id: "s1",
        text: "It must include data like its people, language, and its culture",
        words: [
          { w: "It", m: "Nó (bài nghiên cứu)" },
          { w: "must", m: "phải" },
          { w: "include", m: "bao gồm" },
          { w: "data", m: "dữ liệu/thông tin" },
          { w: "like", m: "như là" },
          { w: "its", m: "của nó" },
          { w: "people", m: "con người" },
          { w: "language", m: "ngôn ngữ" },
          { w: "and", m: "và" },
          { w: "its", m: "của nó" },
          { w: "culture", m: "văn hóa" },
        ],
      },
      {
        id: "s2",
        text: "It may not have enough those information, but still you can find similar ones",
        words: [
          { w: "It", m: "Nó" },
          { w: "may not", m: "có thể không" },
          { w: "have", m: "có" },
          { w: "enough", m: "đủ" },
          { w: "those", m: "những" },
          { w: "information", m: "thông tin" },
          { w: "but", m: "nhưng" },
          { w: "still", m: "vẫn" },
          { w: "you", m: "bạn" },
          { w: "can", m: "có thể" },
          { w: "find", m: "tìm thấy" },
          { w: "similar", m: "tương tự" },
          { w: "ones", m: "những cái/thông tin khác" },
        ],
      },
      {
        id: "s3",
        text: "You can compare these three areas with your own country",
        words: [
          { w: "You", m: "Bạn" },
          { w: "can", m: "có thể" },
          { w: "compare", m: "so sánh" },
          { w: "these", m: "những... này" },
          { w: "three", m: "ba" },
          { w: "areas", m: "lĩnh vực/khu vực" },
          { w: "with", m: "với" },
          { w: "your", m: "của bạn" },
          { w: "own", m: "riêng/chính" },
          { w: "country", m: "quốc gia" },
        ],
      },
      {
        id: "s4",
        text: "Before starting writing, you need to do research and find out more details about the country",
        words: [
          { w: "Before", m: "Trước khi" },
          { w: "starting", m: "bắt đầu" },
          { w: "writing", m: "việc viết" },
          { w: "you", m: "bạn" },
          { w: "need to", m: "cần phải" },
          { w: "do research", m: "làm nghiên cứu" },
          { w: "and", m: "và" },
          { w: "find out", m: "tìm hiểu" },
          { w: "more", m: "thêm/nhiều hơn" },
          { w: "details", m: "chi tiết" },
          { w: "about", m: "về" },
          { w: "the", m: "mạo từ" },
          { w: "country", m: "quốc gia" },
        ],
      },
      {
        id: "s5",
        text: "This comparison can help you find similar understanding between the two nations",
        words: [
          { w: "This", m: "Sự... này" },
          { w: "comparison", m: "so sánh" },
          { w: "can", m: "có thể" },
          { w: "help", m: "giúp" },
          { w: "you", m: "bạn" },
          { w: "find", m: "tìm thấy" },
          { w: "similar", m: "tương đồng" },
          { w: "understanding", m: "sự hiểu biết/thấu hiểu" },
          { w: "between", m: "giữa" },
          { w: "the", m: "mạo từ" },
          { w: "two", m: "hai" },
          { w: "nations", m: "quốc gia/dân tộc" },
        ],
      },
    ],
  },
  // Tiếp tục nối vào mảng quizData trong file dữ liệu của bạn
  {
    id: 6,
    topic: "A famous singer",
    correct_order: ["s1", "s5", "s4", "s3", "s2"],
    sentences: [
      {
        id: "s1",
        text: "Before becoming famous at a young age, he studied art and music at high school",
        words: [
          { w: "Before", m: "Trước khi" },
          { w: "becoming", m: "trở nên" },
          { w: "famous", m: "nổi tiếng" },
          { w: "at", m: "ở/lúc" },
          { w: "a", m: "một" },
          { w: "young", m: "trẻ" },
          { w: "age", m: "tuổi" },
          { w: "he", m: "anh ấy" },
          { w: "studied", m: "đã học" },
          { w: "art", m: "nghệ thuật" },
          { w: "and", m: "và" },
          { w: "music", m: "âm nhạc" },
          { w: "at", m: "tại" },
          { w: "high school", m: "trường trung học" },
        ],
      },
      {
        id: "s2",
        text: "They started to follow him on social media and he is now very famous.",
        words: [
          { w: "They", m: "Họ (mọi người)" },
          { w: "started", m: "đã bắt đầu" },
          { w: "to follow", m: "theo dõi" },
          { w: "him", m: "anh ấy" },
          { w: "on", m: "trên" },
          { w: "social media", m: "mạng xã hội" },
          { w: "and", m: "và" },
          { w: "he", m: "anh ấy" },
          { w: "is", m: "thì" },
          { w: "now", m: "bây giờ" },
          { w: "very", m: "rất" },
          { w: "famous", m: "nổi tiếng" },
        ],
      },
      {
        id: "s3",
        text: "This strange ways of dressing and his songs attracted people's attention",
        words: [
          { w: "This", m: "Những... này" },
          { w: "strange", m: "lạ lùng" },
          { w: "ways", m: "cách thức" },
          { w: "of", m: "về" },
          { w: "dressing", m: "ăn mặc" },
          { w: "and", m: "và" },
          { w: "his", m: "của anh ấy" },
          { w: "songs", m: "các bài hát" },
          { w: "attracted", m: "đã thu hút" },
          { w: "people's", m: "của mọi người" },
          { w: "attention", m: "sự chú ý" },
        ],
      },
      {
        id: "s4",
        text: "During his performances on stage, he likes to wear colorful clothes and paint his face.",
        words: [
          { w: "During", m: "Trong suốt" },
          { w: "his", m: "của anh ấy" },
          { w: "performances", m: "các buổi biểu diễn" },
          { w: "on", m: "trên" },
          { w: "stage", m: "sân khấu" },
          { w: "he", m: "anh ấy" },
          { w: "likes", m: "thích" },
          { w: "to wear", m: "mặc" },
          { w: "colorful", m: "rực rỡ/nhiều màu" },
          { w: "clothes", m: "quần áo" },
          { w: "and", m: "và" },
          { w: "paint", m: "vẽ/hóa trang" },
          { w: "his", m: "của anh ấy" },
          { w: "face", m: "khuôn mặt" },
        ],
      },
      {
        id: "s5",
        text: "During this education, he started to perform on stage",
        words: [
          { w: "During", m: "Trong suốt" },
          { w: "this", m: "này" },
          { w: "education", m: "quá trình học tập" },
          { w: "he", m: "anh ấy" },
          { w: "started", m: "đã bắt đầu" },
          { w: "to perform", m: "biểu diễn" },
          { w: "on", m: "trên" },
          { w: "stage", m: "sân khấu" },
        ],
      },
    ],
  },

  // Tiếp tục nối vào mảng quizData trong file dữ liệu của bạn
  {
    id: 7,
    topic: "Presentation",
    correct_order: ["s2", "s1", "s5", "s4", "s3"],
    sentences: [
      {
        id: "s1",
        text: "Then, we present our topic for five minutes.",
        words: [
          { w: "Then", m: "Sau đó" },
          { w: "we", m: "chúng tôi" },
          { w: "present", m: "thuyết trình" },
          { w: "our", m: "của chúng tôi" },
          { w: "topic", m: "chủ đề" },
          { w: "for", m: "trong" },
          { w: "five", m: "năm" },
          { w: "minutes", m: "phút" },
        ],
      },
      {
        id: "s2",
        text: "First, we prepare materials for our group presentation.",
        words: [
          { w: "First", m: "Đầu tiên" },
          { w: "we", m: "chúng tôi" },
          { w: "prepare", m: "chuẩn bị" },
          { w: "materials", m: "tài liệu" },
          { w: "for", m: "cho" },
          { w: "our", m: "của chúng tôi" },
          { w: "group", m: "nhóm" },
          { w: "presentation", m: "bài thuyết trình" },
        ],
      },
      {
        id: "s3",
        text: "Finally, group members take turns answering the questions.",
        words: [
          { w: "Finally", m: "Cuối cùng" },
          { w: "group", m: "nhóm" },
          { w: "members", m: "thành viên" },
          { w: "take turns", m: "thay phiên nhau" },
          { w: "answering", m: "trả lời" },
          { w: "the", m: "mạo từ" },
          { w: "questions", m: "câu hỏi" },
        ],
      },
      {
        id: "s4",
        text: "After the presentation, the other students ask questions.",
        words: [
          { w: "After", m: "Sau" },
          { w: "the", m: "mạo từ" },
          { w: "presentation", m: "bài thuyết trình" },
          { w: "the", m: "mạo từ" },
          { w: "other", m: "khác" },
          { w: "students", m: "sinh viên/học sinh" },
          { w: "ask", m: "đặt/hỏi" },
          { w: "questions", m: "câu hỏi" },
        ],
      },
      {
        id: "s5",
        text: "During the presentation, we use pictures and our own words to explain the ideas.",
        words: [
          { w: "During", m: "Trong suốt" },
          { w: "the", m: "mạo từ" },
          { w: "presentation", m: "bài thuyết trình" },
          { w: "we", m: "chúng tôi" },
          { w: "use", m: "sử dụng" },
          { w: "pictures", m: "hình ảnh" },
          { w: "and", m: "và" },
          { w: "our", m: "của chúng tôi" },
          { w: "own", m: "riêng/chính" },
          { w: "words", m: "từ ngữ" },
          { w: "to", m: "để" },
          { w: "explain", m: "giải thích" },
          { w: "the", m: "mạo từ" },
          { w: "ideas", m: "ý tưởng" },
        ],
      },
    ],
  },

  // Tiếp tục nối vào mảng quizData trong file dữ liệu của bạn
  {
    id: 8,
    topic: "Workplace Evolution",
    correct_order: ["s3", "s5", "s2", "s4", "s1"],
    sentences: [
      {
        id: "s1",
        text: "Today, companies experiment with shorter workweeks to boost productivity.",
        words: [
          { w: "Today", m: "Ngày nay" },
          { w: "companies", m: "các công ty" },
          { w: "experiment", m: "thử nghiệm" },
          { w: "with", m: "với" },
          { w: "shorter", m: "ngắn hơn" },
          { w: "workweeks", m: "tuần làm việc" },
          { w: "to", m: "để" },
          { w: "boost", m: "thúc đẩy/tăng cường" },
          { w: "productivity", m: "năng suất" },
        ],
      },
      {
        id: "s2",
        text: "Modern workplaces are adopting more flexible work models.",
        words: [
          { w: "Modern", m: "Hiện đại" },
          { w: "workplaces", m: "nơi làm việc" },
          { w: "are adopting", m: "đang áp dụng" },
          { w: "more", m: "nhiều... hơn" },
          { w: "flexible", m: "linh hoạt" },
          { w: "work models", m: "mô hình làm việc" },
        ],
      },
      {
        id: "s3",
        text: "In the past, employees followed strict nine-to-five schedules.",
        words: [
          { w: "In", m: "Trong" },
          { w: "the", m: "mạo từ" },
          { w: "past", m: "quá khứ" },
          { w: "employees", m: "nhân viên" },
          { w: "followed", m: "đã tuân theo" },
          { w: "strict", m: "nghiêm ngặt" },
          { w: "nine-to-five", m: "từ 9 giờ sáng đến 5 giờ chiều" },
          { w: "schedules", m: "lịch trình" },
        ],
      },
      {
        id: "s4",
        text: "Managers now use software to track project progress remotely.",
        words: [
          { w: "Managers", m: "Các nhà quản lý" },
          { w: "now", m: "giờ đây" },
          { w: "use", m: "sử dụng" },
          { w: "software", m: "phần mềm" },
          { w: "to", m: "để" },
          { w: "track", m: "theo dõi" },
          { w: "project", m: "dự án" },
          { w: "progress", m: "tiến độ" },
          { w: "remotely", m: "từ xa" },
        ],
      },
      {
        id: "s5",
        text: "Limited technology once restricted remote work possibilities.",
        words: [
          { w: "Limited", m: "Hạn chế" },
          { w: "technology", m: "công nghệ" },
          { w: "once", m: "đã từng" },
          { w: "restricted", m: "hạn chế/cản trở" },
          { w: "remote work", m: "làm việc từ xa" },
          { w: "possibilities", m: "khả năng/cơ hội" },
        ],
      },
    ],
  },
  // Tiếp tục nối vào mảng quizData trong file dữ liệu của bạn
  {
    id: 9,
    topic: "Music festivals",
    correct_order: ["s4", "s5", "s3", "s1", "s2"],
    sentences: [
      {
        id: "s1",
        text: "He performed for two hours and everyone had great fun.",
        words: [
          { w: "He", m: "Anh ấy (ca sĩ)" },
          { w: "performed", m: "đã biểu diễn" },
          { w: "for", m: "trong" },
          { w: "two", m: "hai" },
          { w: "hours", m: "giờ" },
          { w: "and", m: "và" },
          { w: "everyone", m: "mọi người" },
          { w: "had", m: "đã có" },
          { w: "great", m: "rất nhiều" },
          { w: "fun", m: "niềm vui/sự vui vẻ" },
        ],
      },
      {
        id: "s2",
        text: "The staff there had a busy day, but they were able to close early and watch the famous singer perform.",
        words: [
          { w: "The", m: "mạo từ" },
          { w: "staff", m: "nhân viên" },
          { w: "there", m: "ở đó" },
          { w: "had", m: "đã có" },
          { w: "a", m: "một" },
          { w: "busy", m: "bận rộn" },
          { w: "day", m: "ngày" },
          { w: "but", m: "nhưng" },
          { w: "they", m: "họ" },
          { w: "were able to", m: "đã có thể" },
          { w: "close", m: "đóng cửa" },
          { w: "early", m: "sớm" },
          { w: "and", m: "và" },
          { w: "watch", m: "xem" },
          { w: "the", m: "mạo từ" },
          { w: "famous", m: "nổi tiếng" },
          { w: "singer", m: "ca sĩ" },
          { w: "perform", m: "biểu diễn" },
        ],
      },
      {
        id: "s3",
        text: "Many of them arrived early and visited nearby shops while they were waiting for it to begin.",
        words: [
          { w: "Many", m: "Nhiều" },
          { w: "of", m: "trong số" },
          { w: "them", m: "họ (người tham dự)" },
          { w: "arrived", m: "đã đến" },
          { w: "early", m: "sớm" },
          { w: "and", m: "và" },
          { w: "visited", m: "đã ghé thăm" },
          { w: "nearby", m: "gần đó" },
          { w: "shops", m: "các cửa hàng" },
          { w: "while", m: "trong khi" },
          { w: "they", m: "họ" },
          { w: "were waiting", m: "đang chờ đợi" },
          { w: "for", m: "cho" },
          { w: "it", m: "nó (buổi diễn)" },
          { w: "to begin", m: "bắt đầu" },
        ],
      },
      {
        id: "s4",
        text: "The local authority planned, sponsored, and paid for everything.",
        words: [
          { w: "The", m: "mạo từ" },
          { w: "local authority", m: "chính quyền địa phương" },
          { w: "planned", m: "đã lập kế hoạch" },
          { w: "sponsored", m: "đã tài trợ" },
          { w: "and", m: "và" },
          { w: "paid for", m: "đã chi trả cho" },
          { w: "everything", m: "mọi thứ" },
        ],
      },
      {
        id: "s5",
        text: "Because it was free, more than 5,000 people attended",
        words: [
          { w: "Because", m: "Bởi vì" },
          { w: "it", m: "nó" },
          { w: "was", m: "đã" },
          { w: "free", m: "miễn phí" },
          { w: "more than", m: "hơn" },
          { w: "5,000", m: "năm nghìn" },
          { w: "people", m: "người" },
          { w: "attended", m: "đã tham dự" },
        ],
      },
    ],
  },

  // Tiếp tục nối vào mảng quizData trong file dữ liệu của bạn
  {
    id: 10,
    topic: "End of term project",
    correct_order: ["s3", "s1", "s2", "s4", "s5"],
    sentences: [
      {
        id: "s1",
        text: "Then you need to use images and written work to create a presentation",
        words: [
          { w: "Then", m: "Sau đó" },
          { w: "you", m: "bạn" },
          { w: "need to", m: "cần phải" },
          { w: "use", m: "sử dụng" },
          { w: "images", m: "hình ảnh" },
          { w: "and", m: "và" },
          { w: "written work", m: "bài viết" },
          { w: "to", m: "để" },
          { w: "create", m: "tạo ra" },
          { w: "a", m: "một" },
          { w: "presentation", m: "bài thuyết trình" },
        ],
      },
      {
        id: "s2",
        text: "It needs to include relevant images and your own text about the topic.",
        words: [
          { w: "It", m: "Nó (bài thuyết trình)" },
          { w: "needs to", m: "cần phải" },
          { w: "include", m: "bao gồm" },
          { w: "relevant", m: "liên quan" },
          { w: "images", m: "hình ảnh" },
          { w: "and", m: "và" },
          { w: "your", m: "của bạn" },
          { w: "own", m: "riêng/chính" },
          { w: "text", m: "văn bản/nội dung" },
          { w: "about", m: "về" },
          { w: "the", m: "mạo từ" },
          { w: "topic", m: "chủ đề" },
        ],
      },
      {
        id: "s3",
        text: "For end of term project, you need to choose at least 2 of these",
        words: [
          { w: "For", m: "Cho" },
          { w: "end of term", m: "cuối kỳ" },
          { w: "project", m: "dự án" },
          { w: "you", m: "bạn" },
          { w: "need to", m: "cần phải" },
          { w: "choose", m: "chọn" },
          { w: "at least", m: "ít nhất" },
          { w: "2", m: "hai" },
          { w: "of", m: "trong số" },
          { w: "these", m: "những thứ này" },
        ],
      },
      {
        id: "s4",
        text: "Your presentation offer your key points and you have around 5 minutes to talk",
        words: [
          { w: "Your", m: "Của bạn" },
          { w: "presentation", m: "bài thuyết trình" },
          { w: "offer", m: "đưa ra/trình bày" },
          { w: "your", m: "của bạn" },
          { w: "key", m: "chính/mấu chốt" },
          { w: "points", m: "các điểm/ý" },
          { w: "and", m: "và" },
          { w: "you", m: "bạn" },
          { w: "have", m: "có" },
          { w: "around", m: "khoảng" },
          { w: "5", m: "năm" },
          { w: "minutes", m: "phút" },
          { w: "to", m: "để" },
          { w: "talk", m: "nói/thuyết trình" },
        ],
      },
      {
        id: "s5",
        text: "After this time, other students are able to ask questions and you need to answer them",
        words: [
          { w: "After", m: "Sau" },
          { w: "this", m: "này" },
          { w: "time", m: "thời gian" },
          { w: "other", m: "khác" },
          { w: "students", m: "học sinh" },
          { w: "are able to", m: "có thể" },
          { w: "ask", m: "đặt/hỏi" },
          { w: "questions", m: "câu hỏi" },
          { w: "and", m: "và" },
          { w: "you", m: "bạn" },
          { w: "need to", m: "cần phải" },
          { w: "answer", m: "trả lời" },
          { w: "them", m: "chúng" },
        ],
      },
    ],
  },
  // Tiếp tục nối vào mảng quizData trong file dữ liệu của bạn
  {
    id: 11,
    topic: "The first American woman in space",
    correct_order: ["s3", "s5", "s2", "s4", "s1"],
    sentences: [
      {
        id: "s1",
        text: "Some of those were about growing plants and some animals in a spaceship.",
        words: [
          { w: "Some", m: "Một vài" },
          { w: "of", m: "trong số" },
          { w: "those", m: "những cái đó (thí nghiệm)" },
          { w: "were", m: "đã là" },
          { w: "about", m: "về" },
          { w: "growing", m: "việc trồng" },
          { w: "plants", m: "thực vật/cây cối" },
          { w: "and", m: "và" },
          { w: "some", m: "một vài" },
          { w: "animals", m: "động vật" },
          { w: "in", m: "trong" },
          { w: "a", m: "một" },
          { w: "spaceship", m: "tàu vũ trụ" },
        ],
      },
      {
        id: "s2",
        text: "This is about space and it helps her to become a member of a research team.",
        words: [
          { w: "This", m: "Điều này (khoá đào tạo)" },
          { w: "is", m: "thì" },
          { w: "about", m: "về" },
          { w: "space", m: "vũ trụ" },
          { w: "and", m: "và" },
          { w: "it", m: "nó" },
          { w: "helps", m: "giúp" },
          { w: "her", m: "cô ấy" },
          { w: "to become", m: "trở thành" },
          { w: "a", m: "một" },
          { w: "member", m: "thành viên" },
          { w: "of", m: "của" },
          { w: "a", m: "một" },
          { w: "research", m: "nghiên cứu" },
          { w: "team", m: "đội/nhóm" },
        ],
      },
      {
        id: "s3",
        text: "With the support from parents, Mae went to university to study Science",
        words: [
          { w: "With", m: "Với" },
          { w: "the", m: "mạo từ" },
          { w: "support", m: "sự ủng hộ/hỗ trợ" },
          { w: "from", m: "từ" },
          { w: "parents", m: "cha mẹ" },
          { w: "Mae", m: "Mae (tên nhân vật)" },
          { w: "went to", m: "đã đi đến/nhập học" },
          { w: "university", m: "trường đại học" },
          { w: "to study", m: "để học" },
          { w: "Science", m: "Khoa học" },
        ],
      },
      {
        id: "s4",
        text: "As a part of this group, she traveled in space and did a lot of experiments there",
        words: [
          { w: "As", m: "Với tư cách" },
          { w: "a", m: "một" },
          { w: "part", m: "phần/thành viên" },
          { w: "of", m: "của" },
          { w: "this", m: "này" },
          { w: "group", m: "nhóm" },
          { w: "she", m: "cô ấy" },
          { w: "traveled", m: "đã du hành/đi lại" },
          { w: "in", m: "trong" },
          { w: "space", m: "vũ trụ" },
          { w: "and", m: "và" },
          { w: "did", m: "đã thực hiện" },
          { w: "a lot of", m: "nhiều" },
          { w: "experiments", m: "thí nghiệm" },
          { w: "there", m: "tại đó" },
        ],
      },
      {
        id: "s5",
        text: "Her degree allows her to get a seat on the training course in the USA.",
        words: [
          { w: "Her", m: "Của cô ấy" },
          { w: "degree", m: "bằng cấp" },
          { w: "allows", m: "cho phép" },
          { w: "her", m: "cô ấy" },
          { w: "to get", m: "có được" },
          { w: "a", m: "một" },
          { w: "seat", m: "chỗ ngồi/suất" },
          { w: "on", m: "trong" },
          { w: "the", m: "mạo từ" },
          { w: "training", m: "đào tạo" },
          { w: "course", m: "khóa học" },
          { w: "in", m: "tại" },
          { w: "the", m: "mạo từ" },
          { w: "USA", m: "nước Mỹ" },
        ],
      },
    ],
  },
  // Tiếp tục nối vào mảng quizData trong file dữ liệu của bạn
  {
    id: 12,
    topic: "Artificial Intelligence",
    correct_order: ["s5", "s3", "s2", "s1", "s4"],
    sentences: [
      {
        id: "s1",
        text: "Nowadays, AI engineers build advanced models for complex tasks such as language translation.",
        words: [
          { w: "Nowadays", m: "Ngày nay" },
          { w: "AI", m: "Trí tuệ nhân tạo" },
          { w: "engineers", m: "các kỹ sư" },
          { w: "build", m: "xây dựng" },
          { w: "advanced", m: "tiên tiến/cao cấp" },
          { w: "models", m: "các mô hình" },
          { w: "for", m: "cho" },
          { w: "complex", m: "phức tạp" },
          { w: "tasks", m: "nhiệm vụ/tác vụ" },
          { w: "such as", m: "như là" },
          { w: "language", m: "ngôn ngữ" },
          { w: "translation", m: "dịch thuật" },
        ],
      },
      {
        id: "s2",
        text: "High computational costs previously hindered the development of AI.",
        words: [
          { w: "High", m: "Cao" },
          { w: "computational", m: "tính toán" },
          { w: "costs", m: "chi phí" },
          { w: "previously", m: "trước đây" },
          { w: "hindered", m: "đã cản trở/gây khó khăn" },
          { w: "the", m: "mạo từ" },
          { w: "development", m: "sự phát triển" },
          { w: "of", m: "của" },
          { w: "AI", m: "AI" },
        ],
      },
      {
        id: "s3",
        text: "The early AI systems were limited to simple pattern recognition tasks.",
        words: [
          { w: "The", m: "mạo từ" },
          { w: "early", m: "sơ khai/đầu tiên" },
          { w: "AI systems", m: "hệ thống AI" },
          { w: "were limited", m: "đã bị giới hạn" },
          { w: "to", m: "trong" },
          { w: "simple", m: "đơn giản" },
          { w: "pattern", m: "mẫu/dạng" },
          { w: "recognition", m: "nhận dạng" },
          { w: "tasks", m: "nhiệm vụ" },
        ],
      },
      {
        id: "s4",
        text: "Modern AI tools help businesses to analyze data and make better decisions.",
        words: [
          { w: "Modern", m: "Hiện đại" },
          { w: "AI tools", m: "công cụ AI" },
          { w: "help", m: "giúp" },
          { w: "businesses", m: "các doanh nghiệp" },
          { w: "to analyze", m: "phân tích" },
          { w: "data", m: "dữ liệu" },
          { w: "and", m: "và" },
          { w: "make", m: "đưa ra" },
          { w: "better", m: "tốt hơn" },
          { w: "decisions", m: "quyết định" },
        ],
      },
      {
        id: "s5",
        text: "Over the past decade, artificial intelligence has revolutionized various industries.",
        words: [
          { w: "Over", m: "Trong suốt" },
          { w: "the", m: "mạo từ" },
          { w: "past", m: "vừa qua" },
          { w: "decade", m: "thập kỷ" },
          { w: "artificial intelligence", m: "trí tuệ nhân tạo" },
          { w: "has revolutionized", m: "đã cách mạng hóa" },
          { w: "various", m: "nhiều/khác nhau" },
          { w: "industries", m: "ngành công nghiệp" },
        ],
      },
    ],
  },
  // Tiếp tục nối vào mảng quizData trong file dữ liệu của bạn
  {
    id: 13,
    topic: "University Welcome Day",
    correct_order: ["s2", "s3", "s1", "s5", "s4"],
    sentences: [
      {
        id: "s1",
        text: "These staff members will give you a guided tour in the buildings and our sport facilities in small groups",
        words: [
          { w: "These", m: "Những... này" },
          { w: "staff", m: "nhân viên" },
          { w: "members", m: "thành viên" },
          { w: "will", m: "sẽ" },
          { w: "give", m: "đưa cho/dẫn" },
          { w: "you", m: "bạn" },
          { w: "a", m: "một" },
          { w: "guided", m: "có hướng dẫn" },
          { w: "tour", m: "chuyến tham quan" },
          { w: "in", m: "trong" },
          { w: "the", m: "mạo từ" },
          { w: "buildings", m: "các tòa nhà" },
          { w: "and", m: "và" },
          { w: "our", m: "của chúng tôi" },
          { w: "sport", m: "thể thao" },
          { w: "facilities", m: "cơ sở vật chất" },
          { w: "in", m: "theo" },
          { w: "small", m: "nhỏ" },
          { w: "groups", m: "nhóm" },
        ],
      },
      {
        id: "s2",
        text: "The day will begin at 10 a.m. in the morning with a short presentation.",
        words: [
          { w: "The", m: "mạo từ" },
          { w: "day", m: "ngày" },
          { w: "will", m: "sẽ" },
          { w: "begin", m: "bắt đầu" },
          { w: "at", m: "lúc" },
          { w: "10 a.m.", m: "10 giờ sáng" },
          { w: "in", m: "vào" },
          { w: "the", m: "mạo từ" },
          { w: "morning", m: "buổi sáng" },
          { w: "with", m: "với" },
          { w: "a", m: "một" },
          { w: "short", m: "ngắn" },
          { w: "presentation", m: "bài thuyết trình" },
        ],
      },
      {
        id: "s3",
        text: "At the end of this talk, you will meet the heads of departments and teachers.",
        words: [
          { w: "At", m: "Tại" },
          { w: "the", m: "mạo từ" },
          { w: "end", m: "phần cuối" },
          { w: "of", m: "của" },
          { w: "this", m: "này" },
          { w: "talk", m: "bài nói/thuyết trình" },
          { w: "you", m: "bạn" },
          { w: "will", m: "sẽ" },
          { w: "meet", m: "gặp" },
          { w: "the", m: "mạo từ" },
          { w: "heads", m: "những người đứng đầu/trưởng" },
          { w: "of", m: "của" },
          { w: "departments", m: "các khoa/phòng ban" },
          { w: "and", m: "và" },
          { w: "teachers", m: "giáo viên" },
        ],
      },
      {
        id: "s4",
        text: "This meal will be provided on the second floor of the engineering building",
        words: [
          { w: "This", m: "Này" },
          { w: "meal", m: "bữa ăn" },
          { w: "will", m: "sẽ" },
          { w: "be provided", m: "được cung cấp" },
          { w: "on", m: "tại/trên" },
          { w: "the", m: "mạo từ" },
          { w: "second", m: "thứ hai" },
          { w: "floor", m: "tầng" },
          { w: "of", m: "của" },
          { w: "the", m: "mạo từ" },
          { w: "engineering", m: "kỹ thuật" },
          { w: "building", m: "tòa nhà" },
        ],
      },
      {
        id: "s5",
        text: "During this visit, you will need to stay with these students until lunch break.",
        words: [
          { w: "During", m: "Trong suốt" },
          { w: "this", m: "này" },
          { w: "visit", m: "chuyến thăm/tham quan" },
          { w: "you", m: "bạn" },
          { w: "will", m: "sẽ" },
          { w: "need to", m: "cần phải" },
          { w: "stay", m: "ở lại/đi cùng" },
          { w: "with", m: "với" },
          { w: "these", m: "những... này" },
          { w: "students", m: "sinh viên" },
          { w: "until", m: "cho đến khi" },
          { w: "lunch", m: "bữa trưa" },
          { w: "break", m: "giờ nghỉ" },
        ],
      },
    ],
  },
];
